---
apiVersion: hub.traefik.io/v1alpha1
kind: APIPlan
metadata:
  name: chat-plan
  namespace: chats
  labels:
    {{- include "chats.labels" . | nindent 4 }}
spec:
  title: "Chat Plan"
  description: "A plan with **lower** rate limits and quotas"
  rateLimit:
    limit: 100
    period: 1s
  quota:
    limit: 1000
    period: 750h
---
apiVersion: hub.traefik.io/v1alpha1
kind: APIPlan
metadata:
  name: conversation-plan
  namespace: chats
  labels:
    {{- include "chats.labels" . | nindent 4 }}
spec:
  title: "Deep Conversation Plan"
  description: "A plan with **higher** rate limits and quotas"
  rateLimit:
    limit: 3000
    period: 1s
  quota:
    limit: 1000000
    period: 750h
---
apiVersion: hub.traefik.io/v1alpha1
kind: ManagedApplication
metadata:
  name: admin-application
  namespace: chats
  labels:
    {{- include "chats.labels" . | nindent 4 }}
spec:
  appId: "admins"
  owner: {{ .Values.keycloak.adminId }}
---
apiVersion: hub.traefik.io/v1alpha1
kind: ManagedSubscription
metadata:
  name: admin-subscription
  namespace: chats
  labels:
    {{- include "chats.labels" . | nindent 4 }}
spec:
  managedApplications:
    - name: "admin-application"
  apis:
    {{- if has "openai" .Values.components }}
    - name: "openai-api"
    {{- end }}
    {{- if has "gpt-oss" .Values.components }}
    - name: "gpt-oss-api"
    {{- end }}
  apiPlan:
    name: conversation-plan
  weight: 10
---
apiVersion: hub.traefik.io/v1alpha1
kind: ManagedApplication
metadata:
  name: developer-application
  namespace: chats
  labels:
    {{- include "chats.labels" . | nindent 4 }}
spec:
  appId: "developers"
  owner: {{ .Values.keycloak.developerId }}
---
apiVersion: hub.traefik.io/v1alpha1
kind: ManagedSubscription
metadata:
  name: chat-subscription
  namespace: chats
  labels:
    {{- include "chats.labels" . | nindent 4 }}
spec:
  managedApplications:
    - name: "developer-application"
  apis:
    {{- if has "openai" .Values.components }}
    - name: "openai-api"
    {{- end }}
    {{- if has "gpt-oss" .Values.components }}
    - name: "gpt-oss-api"
    {{- end }}
  apiPlan:
    name: chat-plan
  weight: 10
---
apiVersion: hub.traefik.io/v1alpha1
kind: ManagedApplication
metadata:
  name: agent-application
  namespace: chats
  labels:
    {{- include "chats.labels" . | nindent 4 }}
spec:
  appId: "agents"
  owner: {{ .Values.keycloak.agentId }}
---
apiVersion: hub.traefik.io/v1alpha1
kind: ManagedSubscription
metadata:
  name: agent-subscription
  namespace: chats
  labels:
    {{- include "chats.labels" . | nindent 4 }}
spec:
  managedApplications:
    - name: "agent-application"
  apis:
    {{- if has "openai" .Values.components }}
    - name: "openai-api"
    {{- end }}
    {{- if has "gpt-oss" .Values.components }}
    - name: "gpt-oss-api"
    {{- end }}
  apiPlan:
    name: chat-plan
  weight: 10
