{{- if has "openai" .Values.components }}
---
apiVersion: hub.traefik.io/v1alpha1
kind: API
metadata:
  name: openai-api
  namespace: chats
  labels:
    {{- include "chats.labels" . | nindent 4 }}
    component: openai
spec:
  title: "OpenAI API"
  description: "OpenAI API spec"
  openApiSpec:
    url: https://raw.githubusercontent.com/traefik-workshops/traefik-airlines/refs/heads/main/oas/openapi.yaml
    override:
      servers:
        - url: {{ include "chats.openai.apiUrl" . }}
  cors:
    allowHeadersList:
      - "*"
    allowOriginsList:
      - "*"
    allowMethodsList:
      - "*"
    exposeHeadersList:
      - "*"
    addVaryHeader: true
    allowCredentials: true
    allowOriginListRegex:
      - ".*"
    maxAge: 86400
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: openai-route
  namespace: chats
  labels:
    {{- include "chats.labels" . | nindent 4 }}
    component: openai
  annotations:
    hub.traefik.io/api: openai-api
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: {{ include "chats.openai.hostMatch" . }}
      services:
        - name: openai
          namespace: chats
          port: 443
          scheme: https
          passHostHeader: false
      observability:
        traceVerbosity: detailed
      middlewares:
        - name: cc-authtoken
    - kind: Rule
      match: {{ include "chats.openai.hostMatchCompletions" . }}
      services:
        - name: openai
          namespace: chats
          port: 443
          scheme: https
          passHostHeader: false
      observability:
        traceVerbosity: detailed
      middlewares:
        - name: openai-cc
        - name: cc-authtoken
        {{- if .Values.middlewares.semanticCache.enabled }}
        - name: cc-semantic-cache
        {{- end }}
        {{- if .Values.middlewares.contentGuard.enabled }}
        - name: cc-content-guard
        {{- end }}
        {{- if .Values.middlewares.llmGuards.enabled }}
        {{- if .Values.middlewares.llmGuards.useHubChain }}
        - name: cc-llmguard-chain
        {{- else }}
        {{- if .Values.middlewares.llmGuards.topicControlGuard.enabled }}
        - name: cc-topic-control-guard
        {{- end }}
        {{- if .Values.middlewares.llmGuards.contentSafetyGuard.enabled }}
        - name: cc-content-safety-guard
        {{- end }}
        {{- if .Values.middlewares.llmGuards.jailbreakDetectionGuard.enabled }}
        - name: cc-jailbreak-detection-guard
        {{- end }}
        {{- end }}
        {{- end }}
{{- end }}
