{{- if has "openai" .Values.components }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: openai-cc
  namespace: chats
  labels:
    {{- include "chats.labels" . | nindent 4 }}
    component: openai
spec:
  plugin:
    chat-completion:
      model: gpt-4.1-nano
      allowModelOverride: true
      allowParamsOverride: false
      customResponseHeaderMetrics:
        cache_status: "X-Cache-Status"
      params:
        temperature: 1
        topP: 1
        maxTokens: 2048
        frequencyPenalty: 0
        presencePenalty: 0
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: cc-authtoken
  namespace: chats
  labels:
    {{- include "chats.labels" . | nindent 4 }}
    component: openai
spec:
  headers:
    customRequestHeaders:
      Authorization: {{ .Values.openai.authHeader }}
{{- end }}
