---
apiVersion: hub.traefik.io/v1alpha1
kind: APIPlan
metadata:
  name: lower-ed-plan
  namespace: higher-ed
  labels:
    {{- include "higher-ed.labels" . | nindent 4 }}
    component: common

spec:
  title: "Lower Education Plan"
  description: "A plan with **lower** rate limits and quotas"
  rateLimit:
    limit: 10
    period: 1s
  quota:
    limit: 100
    period: 750h
---
apiVersion: hub.traefik.io/v1alpha1
kind: APIPlan
metadata:
  name: higher-ed-plan
  namespace: higher-ed
  labels:
    {{- include "higher-ed.labels" . | nindent 4 }}
    component: common

spec:
  title: "Higher Education Plan"
  description: "A plan with **higher** rate limits and quotas"
  rateLimit:
    limit: 30
    period: 1s
  quota:
    limit: 1000
    period: 750h
---
apiVersion: hub.traefik.io/v1alpha1
kind: ManagedApplication
metadata:
  name: admin-application
  namespace: higher-ed
  labels:
    {{- include "higher-ed.labels" . | nindent 4 }}
    component: common

spec:
  appId: "admins"
  owner: {{ .Values.keycloak.adminId }} # admin@traefik.io
---
apiVersion: hub.traefik.io/v1alpha1
kind: ManagedSubscription
metadata:
  name: admin-subscription
  namespace: higher-ed
  labels:
    {{- include "higher-ed.labels" . | nindent 4 }}
    component: common

spec:
  managedApplications:
    - name: "admin-application"
  apis:
    - name: financial-aid-api
    - name: housing-assignment-api
    - name: scholarship-api
  apiPlan:
    name: higher-ed-plan
  weight: 10
---
apiVersion: hub.traefik.io/v1alpha1
kind: ManagedApplication
metadata:
  name: developer-application
  namespace: higher-ed
  labels:
    {{- include "higher-ed.labels" . | nindent 4 }}
    component: common

spec:
  appId: "developers"
  owner: {{ .Values.keycloak.developerId }} # developer@traefik.io
---
apiVersion: hub.traefik.io/v1alpha1
kind: ManagedSubscription
metadata:
  name: developer-subscription
  namespace: higher-ed
  labels:
    {{- include "higher-ed.labels" . | nindent 4 }}
    component: common

spec:
  managedApplications:
    - name: "developer-application"
  apis:
    - name: financial-aid-api
    - name: housing-assignment-api
    - name: scholarship-api
  apiPlan:
    name: lower-ed-plan
  weight: 10
---
apiVersion: hub.traefik.io/v1alpha1
kind: ManagedApplication
metadata:
  name: agent-application
  namespace: higher-ed
  labels:
    {{- include "higher-ed.labels" . | nindent 4 }}
    component: common

spec:
  appId: "agents"
  owner: {{ .Values.keycloak.agentId }} # agent@traefik.io
---
apiVersion: hub.traefik.io/v1alpha1
kind: ManagedSubscription
metadata:
  name: agent-subscription
  namespace: higher-ed
  labels:
    {{- include "higher-ed.labels" . | nindent 4 }}
    component: common

spec:
  managedApplications:
    - name: "agent-application"
  apis:
    - name: financial-aid-api
    - name: housing-assignment-api
    - name: scholarship-api
  apiPlan:
    name: lower-ed-plan
  weight: 10
