---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: openai-cc
  namespace: chats
spec:
  plugin:
    chat-completion:
      model: gpt-4.1-nano
      allowModelOverride: true
      allowParamsOverride: false
      customResponseHeaderMetrics:
        cache_status: "X-Cache-Status"
      params:
        temperature: 1
        topP: 1
        maxTokens: 2048
        frequencyPenalty: 0
        presencePenalty: 0
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: cc-authtoken
  namespace: chats
spec:
  headers:
    customRequestHeaders:
      Authorization: OPENAI_AUTH_HEADER