apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - 0-service.yaml
  - 1-middlewares.yaml
  - 2-api.yaml

# Replacements to inject openai-api into dependent resources
replacements:
  # Add openai-api to ManagedSubscription apis lists
  - source:
      kind: API
      name: openai-api
      fieldPath: metadata.name
    targets:
      - select:
          kind: ManagedSubscription
        fieldPaths:
          - spec.apis.[name=openai-api].name
        options:
          create: true
  
  # Add openai-api to APICatalogItem apis lists
  - source:
      kind: API
      name: openai-api
      fieldPath: metadata.name
    targets:
      - select:
          kind: APICatalogItem
        fieldPaths:
          - spec.apis.[name=openai-api].name
        options:
          create: true
  
  # Replace OpenAI-specific variables from ConfigMap
  - source:
      kind: ConfigMap
      name: env-config
      fieldPath: data.OPENAI_API_URL
    targets:
      - select:
          kind: API
          name: openai-api
        fieldPaths:
          - spec.openApiSpec.override.servers.0.url
  
  - source:
      kind: ConfigMap
      name: env-config
      fieldPath: data.OPENAI_HOST_MATCH
    targets:
      - select:
          kind: IngressRoute
          name: openai-route
        fieldPaths:
          - spec.routes.0.match
  
  - source:
      kind: ConfigMap
      name: env-config
      fieldPath: data.OPENAI_HOST_MATCH_COMPLETIONS
    targets:
      - select:
          kind: IngressRoute
          name: openai-route
        fieldPaths:
          - spec.routes.1.match
  
  - source:
      kind: ConfigMap
      name: env-config
      fieldPath: data.OPENAI_AUTH_HEADER
    targets:
      - select:
          kind: Middleware
          name: cc-authtoken
        fieldPaths:
          - spec.headers.customRequestHeaders.Authorization
