{{- if .Values.hoppscotch.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: hoppscotch
  labels:
    {{- include "airlines.labels" . | nindent 4 }}
spec:
  entryPoints:
    {{- toYaml .Values.entryPoints | nindent 4 }}
  routes:
    - kind: Rule
      match: {{ include "airlines.test.hostMatch" . }} && Path(`/collection.json`)
      priority: 1000
      services:
        - name: hoppscotch
          port: 8081
    - kind: Rule
      match: {{ include "airlines.test.hostMatch" . }}
      services:
        - name: hoppscotch
          port: 3000
          passHostHeader: true
{{- end }}
