apiVersion: v2
name: ai-gateway
description: A generic AI Gateway Helm chart for Traefik Hub
type: application
version: 3.2.0
appVersion: "1.0.0"


kubeVersion: ">= 1.27.0-0"

maintainers:
  - name: Traefik SA team
    email: sa@traefik.io

sources:
  - https://github.com/traefik-workshops/traefik-demo

home: https://github.com/traefik-workshops/traefik-demo/tree/main/helm/ai-gateway

keywords:
  - traefik
  - ai-gateway
  - llm
  - demo

dependencies:
  - name: presidio
    version: 3.2.0
    repository: "file://../presidio"
    condition: sharedMiddlewares.contentGuardPresidio.enabled
  - name: weaviate
    version: 17.6.1
    repository: "https://weaviate.github.io/weaviate-helm"
    condition: sharedMiddlewares.semanticCache.enabled
  - name: embeddings
    version: 3.2.0
    repository: "file://../embeddings"
    condition: sharedMiddlewares.semanticCache.enabled
