# Default values for higher-ed helm chart

# Base domain for all services
domain: demo.traefikhub.dev

# Keycloak user IDs and credentials
keycloak:
  adminId: ""  # admin@traefik.io
  developerId: ""  # developer@traefik.io
  agentId: ""  # agent@traefik.io
  clientSecret: "NoTgoLZpbrr5QvbNDIRIvmZOhe9wI0r0"
  adminUsername: "admin@traefik.io"
  adminPassword: "topsecretpassword"

# OIDC credentials
oidc:
  clientId: "traefik"
  clientSecret: ""
