---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: coraza-waf
  labels:
    {{- include "airlines.labels" . | nindent 4 }}
spec:
  plugin:
    coraza:
      directives:
        - SecRuleEngine On
        - SecRequestBodyAccess On
        - SecResponseBodyAccess Off
        - SecRule ARGS "@detectSQLi" "id:942100,phase:2,deny,status:403,msg:'SQL Injection Detected',log,tag:attack-sqli"
        - SecRule ARGS "@detectXSS" "id:941100,phase:2,deny,status:403,msg:'XSS Attack Detected',log,tag:attack-xss"
        - SecRule REQUEST_HEADERS:User-Agent "@contains sqlmap" "id:913100,phase:1,deny,status:403,msg:'Automated Scanner Blocked',log,tag:attack-scanner"
      responseCheck: false
