# Ephemeral by default — the demos' single biggest source of leaked cloud spend.
#
# This chart is the ONLY thing in the observability stack that asks for storage:
# kube-prometheus-stack ships `prometheusSpec.storageSpec: {}` and the tempo chart
# ships `persistence.enabled: false`, so both are already emptyDir. Loki is not. Left
# at chart defaults it creates three PVCs — `storage-loki-0` (10Gi, singleBinary) and
# `export-0`/`export-1-loki-minio-0` (5Gi each, the bundled MinIO's two erasure drives)
# — and on a managed cluster each one is a real, billed cloud disk.
#
# Those disks then outlive the demo. Nothing in terraform owns them: the CSI driver
# provisions them, the PersistentVolume is cluster-scoped, and the reclaim is an
# ASYNCHRONOUS cloud API call made by the CSI controller after the PVC goes away. A
# `terraform destroy` deletes the helm release, then the namespace, then — seconds
# later — the cluster's CSI driver and its node pool. The reclaim never gets to run,
# terraform exits 0, and the disks sit `available` and billing forever. Confirmed on
# AWS twice (3 orphaned EBS volumes per run, exactly these three claims); the same
# shape exists on every cloud the stack runs on. `persistentVolumeClaimRetentionPolicy`
# does NOT save it — the singleBinary StatefulSet already renders `whenDeleted: Delete`
# and its volume leaked anyway, because deleting the PVC promptly is not the same as
# the cloud disk actually being deleted before the controller is torn down.
#
# A demo lives for hours and its logs are regenerated by the next standup, so the fix
# is to not ask for the disk at all. Both stores become emptyDir, mounted at the same
# paths the chart's PVCs used, so the only thing that changes is the medium:
#
#   loki  /var/loki      — required: the container runs readOnlyRootFilesystem, so with
#                          persistence off and no volume there is nowhere to write.
#   minio /export-0,-1   — required: with `persistence.enabled: false` the minio subchart
#                          emits neither volumeClaimTemplates NOR the export volumes, and
#                          `mountPath`-`{0..drivesPerNode-1}` is what `minio server` is
#                          told to use.
#
# Set `persistence = true` to go back to PVCs — and then own the teardown.
#
# range() keeps this a plain map: a `var.persistence ? {} : {...}` conditional does not
# type-check here (the two objects have no common type), and merge() of an empty list is {}.
locals {
  storage_values = merge([for _ in range(var.persistence ? 0 : 1) : {
    singleBinary = {
      persistence       = { enabled = false }
      extraVolumes      = [{ name = "storage", emptyDir = {} }]
      extraVolumeMounts = [{ name = "storage", mountPath = "/var/loki" }]
    }
    minio = {
      persistence = { enabled = false }
      extraVolumes = [
        { name = "export-0", emptyDir = {} },
        { name = "export-1", emptyDir = {} },
      ]
      extraVolumeMounts = [
        { name = "export-0", mountPath = "/export-0" },
        { name = "export-1", mountPath = "/export-1" },
      ]
    }
  }]...)
}

resource "helm_release" "loki" {
  name       = var.name
  namespace  = var.namespace
  repository = "https://grafana.github.io/helm-charts"
  chart      = "loki"
  version    = "v6.42.0"
  timeout    = 900
  atomic     = true

  values = [
    yamlencode({
      deploymentMode = "SingleBinary"
      singleBinary = {
        replicas    = 1
        tolerations = var.tolerations
      }
      loki = {
        commonConfig = {
          replication_factor = 1
        }
        schemaConfig = {
          configs = [{
            from         = "2024-04-01"
            store        = "tsdb"
            object_store = "s3"
            schema       = "v13"
            index = {
              prefix = "loki_index_"
              period = "24h"
            }
          }]
        }
        pattern_ingester = {
          enabled = true
        }
        limits_config = {
          allow_structured_metadata = true
          volume_enabled            = true
        }
        ruler = {
          enable_api = true
        }
      }
      minio = {
        enabled = true
      }
      lokiCanary = {
        enabled = false
      }
      test = {
        enabled = false
      }
      gateway = {
        enabled = false
      }
      ingester = {
        replicas = 0
      }
      querier = {
        replicas = 0
      }
      queryFrontend = {
        replicas = 0
      }
      queryScheduler = {
        replicas = 0
      }
      distributor = {
        replicas = 0
      }
      compactor = {
        replicas = 0
      }
      indexGateway = {
        replicas = 0
      }
      bloomCompactor = {
        replicas = 0
      }
      bloomGateway = {
        replicas = 0
      }
      write = {
        replicas = 0
      }
      read = {
        replicas = 0
      }
      backend = {
        replicas = 0
      }
      chunksCache = {
        enabled = false
      }
    }),
    yamlencode(local.storage_values),
    yamlencode(var.extra_values)
  ]

  set = [
    {
      name  = "loki.auth_enabled"
      value = false
    }
  ]
}
