apiVersion: v2
name: airlines
description: Airlines Demo - Scalar Mock Server APIs with Traefik Hub API Management
type: application
version: 0.3.9
appVersion: "2.0.0"

dependencies:
  - name: keycloak
    version: 0.2.3
    repository: "file://../../keycloak/helm"
    condition: keycloak.enabled
