apiVersion: v2
name: airlines
description: Airlines Demo - Traefik Triple Gateway Pattern
type: application
version: 0.2.2
appVersion: "1.0.0"

dependencies:
  - name: ai-gateway
    version: 0.2.2
    repository: "file://../../ai-gateway/helm"
    condition: ai-gateway.enabled
  - name: keycloak
    version: 0.2.2
    repository: "file://../../keycloak/helm"
    condition: keycloak.enabled
