entryPoints:
  - websecure

global:
  domain: demo.traefik.ai

tools-access:
  dashboard:
    token: ""
    group: "tools"

users-access:
  - name: "admin"
    id: ""
    group: "users"

eventServer:
  image: python:3.11-slim

hoppscotch:
  enabled: false
  image: hoppscotch/hoppscotch:2026.2.0
  jwtSecret: "airlines-demo-jwt-secret-32chars!"
  sessionSecret: "airlines-demo-session-32chars-ok"
  dataEncryptionKey: "airlines-demo-encrypt-32chars-ok"

keycloak:
  enabled: false
  realm:
    enabled: true
    name: traefik
    users:
      - admin
      - user
    advancedUsers:
      - username: user-ahv
        email: user-ahv@traefik.io
        password: topsecretpassword
        groups:
          - platform
        claims: {}
      - username: user-nkp
        email: user-nkp@traefik.io
        password: topsecretpassword
        groups:
          - nkp
        claims: {}
    redirectUris: []
  ingress:
    enabled: true
    domain: "{{ .Values.global.domain }}"
    entrypoint: websecure
  ingressInternal:
    enabled: false
  oidc:
    clientId: ""
    clientSecret: ""
    issuerUrl: ""
