---
apiVersion: hub.traefik.io/v1alpha1
kind: API
metadata:
  name: public-works-api
  namespace: gov
  labels:
    {{- include "gov.labels" . | nindent 4 }}
    component: public-works

spec:
  title: "Public Works API"
  description: "Public Works API spec"
  openApiSpec:
    path: /openapi.yaml
    override:
      servers:
        - url: {{ include "gov.publicWorks.apiUrl" . }}
  cors:
    allowHeadersList:
      - "*"
    allowOriginsList:
      - "*"
    allowMethodsList:
      - "*"
    exposeHeadersList:
      - "*"
    addVaryHeader: true
    allowCredentials: true
    allowOriginListRegex:
      - ".*"
    maxAge: 86400
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: public-works-route
  namespace: gov
  labels:
    {{- include "gov.labels" . | nindent 4 }}
    component: public-works

  annotations:
    hub.traefik.io/api: public-works-api
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: {{ include "gov.publicWorks.hostMatch" . }}
      services:
        - name: public-works-app
          namespace: gov
          port: 3000
          passHostHeader: false
      observability:
        traceVerbosity: detailed
