---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: gpt-oss-cc
  namespace: chats
spec:
  plugin:
    chat-completion:
      model: openai/gpt-oss-20b
      allowModelOverride: false
      allowParamsOverride: false
      customResponseHeaderMetrics:
        cache_status: "X-Cache-Status"
      params:
        temperature: 1
        topP: 1
        maxTokens: 2048
        frequencyPenalty: 0
        presencePenalty: 0
