apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - 0-service.yaml
  - 1-middlewares.yaml
  - 2-api.yaml

# Replacements to inject gpt-oss-api into dependent resources
replacements:
  # Add gpt-oss-api to ManagedSubscription apis lists
  - source:
      kind: API
      name: gpt-oss-api
      fieldPath: metadata.name
    targets:
      - select:
          kind: ManagedSubscription
        fieldPaths:
          - spec.apis.[name=gpt-oss-api].name
        options:
          create: true
  
  # Add gpt-oss-api to APICatalogItem apis lists
  - source:
      kind: API
      name: gpt-oss-api
      fieldPath: metadata.name
    targets:
      - select:
          kind: APICatalogItem
        fieldPaths:
          - spec.apis.[name=gpt-oss-api].name
        options:
          create: true
  
  # Replace GPT-OSS-specific variables from ConfigMap
  - source:
      kind: ConfigMap
      name: env-config
      fieldPath: data.GPT_OSS_EXTERNAL_NAME
    targets:
      - select:
          kind: Service
          name: gpt-oss
        fieldPaths:
          - spec.externalName
  
  - source:
      kind: ConfigMap
      name: env-config
      fieldPath: data.GPT_OSS_API_URL
    targets:
      - select:
          kind: API
          name: gpt-oss-api
        fieldPaths:
          - spec.openApiSpec.override.servers.0.url
  
  - source:
      kind: ConfigMap
      name: env-config
      fieldPath: data.GPT_OSS_HOST_MATCH
    targets:
      - select:
          kind: IngressRoute
          name: gpt-oss-route
        fieldPaths:
          - spec.routes.0.match
  
  - source:
      kind: ConfigMap
      name: env-config
      fieldPath: data.GPT_OSS_HOST_MATCH_COMPLETIONS
    targets:
      - select:
          kind: IngressRoute
          name: gpt-oss-route
        fieldPaths:
          - spec.routes.1.match
