{{- if .Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  namespace: {{ include "keycloak.namespace" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
    operator.keycloak.org/component: watched-secret
type: Opaque
data:
  username: {{ "postgres" | b64enc }}
  password: {{ .Values.postgres.password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: {{ include "keycloak.namespace" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.keycloak.adminUser | b64enc }}
  password: {{ .Values.keycloak.adminPassword | b64enc }}
{{- end }}
